name: rwa

services:
  rwa-solitaire:
    container_name: rwa-solitaire
    build:
      context: ./rwa-solitaire
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - public-network
    volumes:
      - ./rwa-solitaire:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rwa-solitaire-api
    restart: unless-stopped
    command: ng serve --host 0.0.0.0 --port 4200

  rwa-solitaire-api:
    container_name: rwa-solitaire-api
    build:
      context: ./rwa-solitaire-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - public-network # for dev purposes remove later
      - internal-network
    volumes:
      - ./rwa-solitaire-api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rwa-solitaire-db
    restart: unless-stopped
    env_file:
      - ./.env
    command: nest start --watch

  rwa-solitaire-db:
    container_name: rwa-solitaire-db
    image: postgres:17-alpine
    networks:
      - public-network # for dev purposes remove later
      - internal-network
    ports:
     - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  public-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true

volumes:
  postgres_data: